// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUj4JelKmiUxNdyWZZ-D9-rv4HEg_5TFM',
    appId: '1:43824056087:web:2213cfc33eac65cbb21952',
    messagingSenderId: '43824056087',
    projectId: 'real-time-chat-c8a21',
    authDomain: 'real-time-chat-c8a21.firebaseapp.com',
    storageBucket: 'real-time-chat-c8a21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77x8B4ME-CkuUwOU5Qo1UYLXqeN3Ilqo',
    appId: '1:43824056087:android:69c3a9b72e144ac3b21952',
    messagingSenderId: '43824056087',
    projectId: 'real-time-chat-c8a21',
    storageBucket: 'real-time-chat-c8a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDriVf_YmaAS_o1ZlynusItvmC4RQaBYQ4',
    appId: '1:43824056087:ios:bcfcb0cfea11a9f9b21952',
    messagingSenderId: '43824056087',
    projectId: 'real-time-chat-c8a21',
    storageBucket: 'real-time-chat-c8a21.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDriVf_YmaAS_o1ZlynusItvmC4RQaBYQ4',
    appId: '1:43824056087:ios:bcfcb0cfea11a9f9b21952',
    messagingSenderId: '43824056087',
    projectId: 'real-time-chat-c8a21',
    storageBucket: 'real-time-chat-c8a21.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUj4JelKmiUxNdyWZZ-D9-rv4HEg_5TFM',
    appId: '1:43824056087:web:7fe15dfb8c93cdf1b21952',
    messagingSenderId: '43824056087',
    projectId: 'real-time-chat-c8a21',
    authDomain: 'real-time-chat-c8a21.firebaseapp.com',
    storageBucket: 'real-time-chat-c8a21.appspot.com',
  );
}
